development:
  paypal_api_username: "store_1233166355_biz_api1.thirdmode.com"
  paypal_api_password: "1233166361"
  paypal_api_signature: "ALZ2S3NXdLgg9g1ENcUy0awyGQAfAQk88a4VgQF0kt2yFDbnZ9SZjIAw"
  paypal_api_mode: "sandbox"
  paypal_api_secret: s5a8l4a9
  paypal_express_payment_action: "Authorization"
  paypal_standard_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  paypal_receiver_email: "store_1233166355_biz@thirdmode.com"
  paypal_cert_id: K8LH9JVM2JHXC
  paypal_ipn_url: "https://store/paypal/notify"
  paypal_callback_url: "https://store/paypal/update"
  paypal_return_url: "https://store/paypal/express_confirm"
  paypal_cancel_url: "https://store/paypal/express_cancel"
  braintree_url: "https://secure.braintreepaymentgateway.com/api/transact.php"
  braintree_key: "UVgCejU48ANga4mKF77WFXfm2yUve76W"
  braintree_key_id: "776320"
  braintree_username: "testapi"
  braintree_password: "password1"
  braintree_direct_sale: "Checkout with Braintree Direct Post"
  ups_access_key: 6C5D1F0A80EEC640
  ups_login: lydianblues
  ups_password: aviva0527

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl
  braintree_url: "https://secure.braintreepaymentgateway.com/api/transact.php"
  braintree_key: "UVgCejU48ANga4mKF77WFXfm2yUve76W"
  braintree_key_id: "776320"
  braintree_username: "testapi"
  braintree_password: "password1"
  braintree_direct_sale: "Checkout with Braintree Direct Post"
  ups_access_key: 6C5D1F0A80EEC640
  ups_login: lydianblues
  ups_password: aviva0527

production:
  paypal_email: foo@example.com
  paypal_secret: supersecret
  paypal_cert_id: KLHZSK326HEDS
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
  braintree_url: "https://secure.braintreepaymentgateway.com/api/transact.php"
  braintree_username: "testapi"
  braintree_password: "password1"
  braintree_direct_sale: "Checkout with Braintree Direct Post"
